### PR TITLE
 Fix custom extension wiring

### LINKED ISSUE #6: Troubleshooting custom extension
Im having problems with a custom sanitizer extension that i created for a project im working on. The extension is manually register with the tag name using YAML like this:

```
    app.sanitizer.iframe_custom:
        class: App\Sanitizer\CustomIframeExtension
        tags:
          - { name: html_sanitizer.extension }
```
The problem its that this extension is not register though the sanitizer builder.

I debug the code and i found that in the HtmlSanitizerExtension when it call to "findTaggedServiceIds('html_sanitizer.extension')" my sanitizer extension service its not found.

If i debug my kernel, and use the findTaggedServiceIds('html_sanitizer.extension') in my Kernel.php its found the service by tag... its like when HtmlSanitizerExtension is loaded my services arent currently loaded.

Some suggestion of what can i do?

Thanks and regards!

### PR DESCRIPTION
**Pull request by tgalopin**
Fix https://github.com/tgalopin/html-sanitizer-bundle/issues/6

@stof I'd love your review :) ! The most important part is the CompilerPass and the extension changes, the rest is mainly tests refactoring and improvements to expose the problem.

### CODE REVIEW

**Comment by stof** [comment]
Looks good to me

**Comment by alex-bacart** [comment]
@tgalopin can you please tell when this PR will be released (version 1.1.2 probably)? Because now it's only in `dev-master`.

**Comment by tgalopin** [comment]
Let's release it now :) .

**Comment by alex-bacart** [comment]
Thanks a lot ;)

**Pull request merged**
